All latest changes
semik997/Movie-Serch-App pull request #1
Opened 2022-01-21 15:14 UTC by semik997

2022-01-24 10:59 UTC, PaszhaBiceps requested changes
Пройдись по комментам и пофиксил. И глобально - избегай ассершнов, приведи экраны к одно структуре (что бы каши не было) и старайся делать меньше экстернов (особенно там где это не нужно). Экстешны чудесно меняются на марки и ты не теряешь в читаемости.

2022-01-24 10:59 UTC, PaszhaBiceps commented on CoreData/FavoriteFilm+CoreDataProperties.swift
> +    @NSManaged public var url: String?
Почему все поля вынесены в экстеншн и отельным файлом?
На будущее - кол-во экстеншнов лучше сокращать по возможности. Если их сильно много будет это отрицательно скажется на времени компиляции.

2022-01-24 10:59 UTC, PaszhaBiceps commented on CoreData/FavoriteFilm+CoreDataProperties.swift
> +extension FavoriteFilm : Identifiable {
Наследование протоколов лучше делать для основного класса.
И тут вопрос - зачем этому объекту быть Identifiable?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App.xcodeproj/xcuserdata/semenkolesnikov.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
> +      <BreakpointProxy
Займись файлом gitingnore, что бы этого всего не было в комметах.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App.xcodeproj/xcuserdata/semenkolesnikov.xcuserdatad/xcschemes/xcschememanagement.plist
> +		<key>Promises (Playground) 1.xcscheme</key>
gitingnore

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +        let appDelegate = UIApplication.shared.delegate as! AppDelegate
Не ассерти каст shared.delegate в AppDelegate. Это потенциальный креш.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +        return appDelegate.persistentContainer.viewContext
Зачем в ячейке контекст кор даты? Его тут быть не должно?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +    @IBAction func likeButton(_ sender: UIButton) {
Старайся делать функции, аутлеты и экшны - приватными (если тебе не нужно будет использовать что либо вне ячейки).

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +            delegate?.selectCell(isFavorite, idFilm: idFilm, url: url, name: name,
Зачем в делегате возвращать ВСЕ что есть если по факту нужны айди и новый статус?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +            isFavorite = !isFavorite
Это должно храниться в модели (да, я помню что там оно уже есть) и модифицироваться вне ячейки.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +        self.secondAPI.fetchShowRaiting(forShow: imdb ?? "") { [self] currentShowIMDb in
Апишка не должна вызываться из ячейки, по крайней мере этот случай так точно. Сколько запросов у тебя уйдет если в выдаче будет 1000 ячеек?
Эту информацию ты должен получать вне ячейки и просто ее туда отдавать.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +    func loadDataFavorite(film: FavoriteFilm) {
Нужно сделать что бы у тебя была одна моделька для всего. Потому что по факту что обычная моделька, что фаворит - это одно и тоже.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +    func getImage(from string: String) -> UIImage? {
Возвращай здесь в случае ошибок и прочего плейсхолдер вместо реальной картинки.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +        let appDelegate = UIApplication.shared.delegate as! AppDelegate
Снова форс анврап аппарат делегата.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +    var filmsFav: [FavoriteFilm] = []
Как я писал выше - делай все проперти приватными.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +            self.favoriteCollectionView.reloadData()
Вынеси всю работу из экшна в отдельную функция и вызывай именно ее. Так будет чище.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +            self.favoriteCollectionView.reloadData()
Зачем перезагружать таблицу в этом случае?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +        alertController.addAction(yes)
Если хочешь прямо красиво - можно не инициализировать экшны отдельно, а создавать их прямо здесь.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +                film = filtredFilms[indexPath[0].row]
Почему здесь всегда берется 0 индекс? А что будет если массив filtredFilms пустой?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +                film = filmsFav[indexPath[0].row]
Аналогично с верхним.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +            let MoreInfoFavoritesTableVC = nav.topViewController as! MoreInfoViewController
Два форс анврапа подряд, поправь.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +        if segue.identifier == "popVC" {
Вынеси когда будет время идентификаторы сегью в константы, так будет чище и лучше.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +        self.small = small
Сделай enum который будет отвечать за состояние интерфейса. 3 бульки выглядят страшно.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +            presentAlertController(withTitle: "Do you sure?", message: nil, style: .alert,
Неправильно написал тайтл.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +            if self.small ?? false {
Возвращаемся к enum для размера. С ним это будет выглядеть намного чище.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/InfoTableViewController.swift
> +        preferredContentSize = CGSize(width: 170, height: tableView.contentSize.height)
Почему тут не вызывается super.viewWillLayoutSubviews?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/InfoTableViewController.swift
> +    {
Не переноси скобки на другую строчку без необходимости, выглядит так себе.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/InfoTableViewController.swift
> +    @IBAction func exit(_ sender: UIButton) {
Наведи порядок в коде. У тебя в перемешку и делегаты и все что хочешь. И в целом приведи структуру экранов и прочих сущностей к одному знаменателю.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +    var secondAPI = SecondAPI()
1. Сделай все приватным, как я уже несколько раз писал выше.
2. Что таке networkManager понятно. А что такое SecondAPI? За что она отвечает?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +    var big: Bool?
Enum.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            self.oneFilm = try context.fetch(FavoriteFilm.fetchRequest())
Название проперти не отражает того что она делает. И сразу вопрос - зачем это тут?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +        let appDelegate = UIApplication.shared.delegate as! AppDelegate
Снова форс анврап. И вообще, если тебе нужно взаимодействовать с кор датой в нескольких местах, не проще ли сделать отдельную сущность которая будет отвечать за это и предоставить другим классам только некоторые вещи?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            findImage.isHidden = false
Опять таки неймниг, за что отвечает findImage?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            self.collectionViewSpace.reloadData()
Зачем здесь перезагрузка коллекции?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            let film = films[indexPath[0].row]
Почему здесь берется именно 0 индекс?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +                // Check count symbol
Старайся меньше комментировать очевидный код.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +                    // need add timer in this fragment
В таких случаях оставляй себе TODO. Что бы они прям тебе о себе напоминали, пиши их так - #warning("TODO: *Some stuff to do*").

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            likeFilms.imdb = imdb
Зачем здесь перезаписывать все поля?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +        return image
Тут тоже - плейсхолдер в случае ошибки и т.п.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            if self.small ?? false {
Enum.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +    func NKPlaceholderImage(image: UIImage?, imageView: UIImageView?, imgUrl: String, compate:@escaping (UIImage?) -> Void) {
Что это и зачем?

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/SettingViewController.swift
> +    var small = false
Enum.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/Delegate/Film.swift
> +        var isFavorite: Bool?
Вынеси это в Film через кастомные декодер, как я тебе и говорил.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/Delegate/Film.swift
> +                return try! PropertyListDecoder().decode([Films.Film].self, from: data as! Data)
Не ассерти. Как я уже писал - это потенциальные креши.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/Delegate/Film.swift
> +//    }
Чисти комменты и закомментированный код если они не нужны и не несут никакой ценности.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/Delegate/SceneDelegate.swift
> +        let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
Снова ассершн.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/Delegate/SecondAPI.swift
> +    func fetchShowRaiting(forShow show: String, completionHandler: @escaping (Films.FilmIMDb) -> Void) {
Зачем отдельный аги класс для одного запроса (и парсер)? Перенеси это все в NetworkingManager.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/MoreInfoViewController.swift
> +                application.open(webURL! as URL)
Снова ассершны.

2022-01-24 10:59 UTC, PaszhaBiceps commented on Movie Search App/MoreInfoViewController.swift
> +                application.open(webURL! as URL)
Ассрешны.

2022-01-24 11:02 UTC, semik997 commented on CoreData/FavoriteFilm+CoreDataProperties.swift
> +    @NSManaged public var url: String?
Это создалось автоматически, я в ручную изменения не вносил

2022-01-24 11:07 UTC, semik997 commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +        return appDelegate.persistentContainer.viewContext
Убрал

2022-01-24 11:14 UTC, semik997 commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +            delegate?.selectCell(isFavorite, idFilm: idFilm, url: url, name: name,
Что бы не создавать новый делегат с меньшими 2мя переменными, которые передаются в том который есть

2022-01-24 11:18 UTC, semik997 commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +    func loadDataFavorite(film: FavoriteFilm) {
Разные, так как на меин экран загружаются данные с парсинга, а с фаворт загружаются данные из кор даты

2022-01-24 11:24 UTC, semik997 commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +            self.favoriteCollectionView.reloadData()
Что бы вернуть заполненную кнопку лайка а не оставлять пустой

2022-01-24 11:25 UTC, semik997 commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +                film = filtredFilms[indexPath[0].row]
То соответственно некуда будет переходить и нечего открывать, так как этот сигвей открывает подробную информацию о фильме
Если элементов не будет, значит и нечего будет открывать и некуда переходить

2022-01-24 11:26 UTC, semik997 commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +                film = filmsFav[indexPath[0].row]
Так же, если нет фильмов, то и искать нечего и ничего не отобразиться

2022-01-24 11:29 UTC, semik997 commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +            presentAlertController(withTitle: "Do you sure?", message: nil, style: .alert,
Не совсем понял замечание, можешь, пожалуйста, подробнее объяснить что не верно написано

2022-01-24 11:30 UTC, semik997 commented on CoreData/FavoriteFilm+CoreDataProperties.swift
> +extension FavoriteFilm : Identifiable {
Файл был создан автоматически, ничего сам не вносил

2022-01-24 11:41 UTC, semik997 commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +    var secondAPI = SecondAPI()
SecondAPI отвечает за рейтинг imdb, который я дополнительно запрашиваю с RapidAPI

2022-01-24 11:45 UTC, semik997 commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            self.oneFilm = try context.fetch(FavoriteFilm.fetchRequest())
Лишняя, убрал

2022-01-24 11:48 UTC, semik997 commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            findImage.isHidden = false
Отображение картинки бек граунда, если нет никакой информации то она видима, если есть хотя бы 1 результат, то невидима

2022-01-24 11:52 UTC, semik997 commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            self.collectionViewSpace.reloadData()
Что-то на подобии видимой перезагрузки экрана для пользователя

2022-01-24 11:56 UTC, semik997 commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            let film = films[indexPath[0].row]
Индексация экрана с 0 элемента
Так же без 0 индекса пишет что row не принадлежит indexPath

2022-01-24 12:00 UTC, semik997 commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            likeFilms.imdb = imdb
Происходит перезапись для сохранения в кор дату

2022-01-24 12:04 UTC, semik997 commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +    func NKPlaceholderImage(image: UIImage?, imageView: UIImageView?, imgUrl: String, compate:@escaping (UIImage?) -> Void) {
Функция для скачивания картинок и последующего сохранения их в кор дату, что бы можно было просматривать их в оффлайн режиме

2022-01-25 10:17 UTC, semik997 commented on Movie Search App/Delegate/SecondAPI.swift
> +    func fetchShowRaiting(forShow show: String, completionHandler: @escaping (Films.FilmIMDb) -> Void) {
Так как парсит с другого апи и по другой структуре

2022-01-26 12:22 UTC, PaszhaBiceps requested changes
Пробежался - уже лучше. Я добавил еще пачку комментов - пройдись по ним.

2022-01-26 12:22 UTC, PaszhaBiceps commented on CoreData/FavoriteFilm+CoreDataProperties.swift
> +    @NSManaged public var url: String?
Тогда перенеси все проперти в сам класс и удали лишние экстеншны, они тут ни к чему.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/API/RapidApiManager.swift
> +    private func parseJSONRaitinig(withData data: Data) -> Films.FilmIMDb? {
Как сделаешь что что делаешь сейчас - напиши универсальный парсер для Codable объектов (подсказка - на дженериках). Что бы избежать подобного дублирования кода в дальнейшем.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +            delegate?.selectCell(isFavorite, idFilm: idFilm, url: url, name: name,
А зачем изначально нужна вся инфа? По хорошему если тебе нужен конкретный объект - передай айдишник нужного фильма/обьекта и достань его из массива в делегате.
И если ты используешь одну и ту же функцию делегата для двух разных действий - лучше так не делать (при работе в команде или если после тебя кто-то будет что-то делать это может вводить в заблуждение и приведет к трате времени на ненужный инвестигейт и курение кода). Лучше расширять делегат по мере необходимости и передать в функции минимально необходимое кол-во инфы/параметров.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +    private func getContext() -> NSManagedObjectContext {
Я там где-то писал по поводу сущности которая будет взаимодействовать с кор датой. Ты не делал это еще?
Ну и по классике - ассершн убери 👌

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +//    func uploadImage(photo: UIImage, completion: @escaping (Result<URL, Error>) -> Void) {
Если это не нужно - удали.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            findImage.isHidden = false
Назови ее тогда чем то вроде noContentImageView, что бы было понятно за что она отвечает. И вообще (как я уже писал) - следи за неймингом. Имя переменной должно отражать то за что она отвечает.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            self.collectionViewSpace.reloadData()
Можешь оставить если считаешь что это реально нужно.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            let film = films[indexPath[0].row]
Логично, так как ты из коллекции получаешь массив IndexPath.  Сделай тогда проверку пустой массив или нет.
И вопрос - у твоей коллекции сингл или мультипл селекшн?

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/Model+Constants/Constants.swift
> +let showDetail = "showDetail"
Закатай это в структуру типа Segues, что бы было понятнее что это и зачем.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +            self.favoriteCollectionView.reloadData()
То есть ты по тапу на кнопку сразу меняешь состояние? Учитывая что у тебя есть алерт что бы подтвердить действие это можно не делать и тем самым лишний раз ничего не перезагружать.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +                film = filtredFilms[indexPath[0].row]
В общем подумай как сделать переходы чище. Потому что сейчас ты зависишь от выбранных ячеек, а не должен.

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/FavoritesCollectionVC.swift
> +    enum ChooseSize {
Да, ты в итоге сделал не так enum как я имел ввиду. Смотри, ты должен передавать не 3 бульки, а 1 енам кейс. И по этому кейсу ты уже будешь ставить нужный сайз (сам размер сделай комьпьютед велью самого енама).

2022-01-26 12:22 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
> +    func loadDataFavorite(film: FavoriteFilm) {
Ты же можешь избежать этого сделай init в одной модельку с помощью другой (для обоих классов). Тем самым ты будешь работать, скажем, только с Film, а FavoriteFilm нужна будет толко что бы достать и сохранить данные в кор дату.
Обдумай это и сделай красиво 😏

2022-01-26 12:31 UTC, semik997 commented on Movie Search App/CollectionVC/MainCollectionVC.swift
> +            let film = films[indexPath[0].row]
Проверку сделаю
Я правильно ли понимаю твой вопрос:
"И вопрос - у твоей коллекции сингл или мультипл селекшн?"
 Ты имеешь в виду можно ли у меня выбрать несколько ячеек или только 1?

2022-01-27 10:40 UTC, merged