125,127 new class core data, made segue clean
semik997/Movie-Serch-App pull request #4
Opened 2022-01-27 15:41 UTC by semik997

2022-02-08 09:27 UTC, PaszhaBiceps requested changes

2022-02-08 09:27 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
>  protocol FavoriteDeletProtocol: AnyObject {
Опечатка.

2022-02-08 09:27 UTC, PaszhaBiceps commented on Movie Search App/CollectionVC/CollectionViewCell.swift
>  protocol FavoriteDeletProtocol: AnyObject {
Используй более правильный неймниг (для ячейки и протокола).

2022-02-08 11:16 UTC, semik997 commented
Внёс  все оговоренные правки

2022-02-08 13:27 UTC, semik997 commented
Сделал правки, которые ранее обсуждали

2022-02-09 08:47 UTC, PaszhaBiceps approved these changes

2022-02-09 08:47 UTC, merged